# Generated by Django 2.1.7 on 2019-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_etud_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='etud',
            name='prenom',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
    ]
