# Generated by Django 2.1.7 on 2019-03-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0003_etud_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='date',
            field=models.DateField(default=True),
            preserve_default=False,
        ),
    ]
