# Generated by Django 2.1.7 on 2019-03-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0004_school_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='date',
        ),
    ]
