# Generated by Django 2.1.7 on 2019-03-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livrision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=250)),
                ('time', models.TimeField()),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('qte', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='livrision',
            name='produite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ap.Produite'),
        ),
    ]
