# Generated by Django 2.1.7 on 2019-03-17 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap', '0002_auto_20190317_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrision',
            name='produite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produite', to='my_ap.Produite'),
        ),
    ]
