# Generated by Django 2.1.7 on 2019-03-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap', '0003_auto_20190317_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produite',
            name='date',
        ),
    ]
