# Generated by Django 2.1.7 on 2019-03-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ap', '0004_remove_produite_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produite',
            name='qte',
            field=models.PositiveIntegerField(),
        ),
    ]
